### ISSUE TITLE
New S64's

### ISSUE THREAD

**Issue by Sportsbadger** [jbroutier/whatisflying-db#139]
Hi - I didn't want to edit your CSV without being able to sort it by ICAO so here are some manual additions for you

N792HT,AAC0034,S-64 Skycrane/CH-54 Tarhe,Sikorsky,CH-54A Tarhe,64039,Helicopter Transport Services
N917HT,A99E3D,S-64 Skycrane/CH-54 Tarhe,Sikorsky,CH-54B Tarhe,64076,Helicopter Transport Services
I-CFAI,A1822F,S-64 Skycrane/CH-54 Tarhe,Erickson,S-64F Skycrane,64067,Vigili del Fuoco

**Comment by jbroutier** [comment]
Hi,

Thanks a lot! Added in commit 1d5eafd.
