### ISSUE TITLE
Incorrect ICAO 24-bit code

### ISSUE THREAD

**Issue by BhavyeMathur** [jbroutier/whatisflying-db#149]
The '4b169c' 24-bit ICAO code seems to refer to 2 different aircraft:

`[('4b169c', 'HB-IOQ', 'Airbus', 'A320-214', 'A320', '3422', 'L2J', 'BHP', None, None, None)]`

and

`[('4b169c', 'D-ATUM', 'Boeing', '737-800', 'B738', '963', 'L2J', 'TOM', '2001-01-01', '2029-05-20', '2001-01-01')]`

After a bit of research, I think that the Boeing code is supposed to be `3c0ca5` (https://planefinder.net/data/aircraft/D-ATUM). I could be wrong, but it would be great if you could check this out.

**Comment by jbroutier** [comment]
Hello @BhavyeMathur,

Thanks for the report!

Indeed the Boeing 737-800 with the 24-bit address `4b169c` is not correct. The aircraft with registration `D-ATUM` is already present in the DB with the correct `3c0ca5` address, so I deleted the duplicated/erroneous data.
