### ISSUE TITLE
Completed Aircraft Engines Database

### ISSUE THREAD

**Issue by BhavyeMathur** [jbroutier/whatisflying-db#152]
For a project that my teammates and I are working on, we needed a complete aircraft engines database. We came across the `aircraft_models.csv` file in this repository and worked towards adding in data for all the aircraft models taken from the `aircraft/manufacturer.csv` database.

Here's a [link](https://github.com/The-CFR-Project/AircraftEnginesDatabase) to our GitHub repo. Let me know if you'd be interested in merging the database with your own! We can't guarantee that all the values are completely accurate, but we have tried our best to verify them. The values also meet the contributing guidelines.

Thanks for the open-source project! it's been really helpful to us.

**Comment by jbroutier** [comment]
Hello @BhavyeMathur,

For sure, I will be interested by your data.

Contributions are always welcome! Feel free to send a pull request if you have time to do so.

**Comment by jbroutier** [comment]
#157
